# Generated by Django 2.0 on 2017-12-13 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
