# Generated by Django 2.0 on 2017-12-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171213_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.IntegerField()),
                ('service', models.CharField(max_length=10)),
            ],
        ),
    ]
